services:
  backend:
    build:
      context: ./server
    container_name: tourism-wallet-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
    container_name: tourism-wallet-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend